version: '3.3'

services:
  test:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    image: ${IMAGE:-pip/test}
    command: ${TEST_CMD:-npm test}
    depends_on:
      - mongo
      - memcached
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
